### ISSUE TITLE
Update PS icon with new colored/facing directions icons? from CorruptEagle

### ISSUE THREAD

**Issue by IceLancerSR** [Kaldaien/UnX#11]
Hey there. I just noticed that u have two the same dds files, or at least they look the same to me :)
While CorruptEagle updated his buttons with gorgeous direction points dpads + colors
http://steamcommunity.com/app/359870/discussions/0/364041517007524857/?ctp=34#c364041776192957143

preview:
https://drive.google.com/file/d/0B2gETAAsqGmvQXZBMDhFU0VXaWM/view
DDS
https://drive.google.com/file/d/0B2gETAAsqGmvS1BoM0s0aEZIZW8/view

Just so this dont get lost, i would say they are best of all for now

Thanks!

**Comment by Kaldaien** [comment]
There's a problem with doing this to the D-Pad, and that's that there is supposed to be a little glow mask for the directional buttons.

You may need to tinker with your image editing software to see them, but they're there and in this .dds, the little glowing outline is the original shape while the D-Pad has been radically altered. I think Final Fantasy X-2 is the only game that uses this feature, but because 0.1.1 is adding FFX-2 support, I should point this out.

**Comment by Continuity28** [comment]
I just want to point out that the texture in question is not my texture.  CorruptEagle made the texture that had the D-pad icons.

The ones I made only changed the four main buttons (keeping the same outline) and the L/R 1/2 buttons for my PS version, which also had the same outlines.  I don't think any of my three textures would conflict with anything, since the outlines are the same.

**Comment by IceLancerSR** [comment]
i am sorry ,yeah i was idiot..
i was reading something u said and brainlesly used ur name instead of authors..
