### ISSUE TITLE
Please use Home Directory (%userprofile%) to store config/log/etc files 

### ISSUE THREAD

**Issue by MeStinkBAD** [Kaldaien/UnX#38]
Placing the config and log files created by UnX in the home directory would allow you to include premade .inis file without over writing the users existing custom .inis stored in the home dir. It also would avoid possible UAC conflicts caused by writing to a potential system directory. And it would make it easy for users to back up their custom configs and injections. 

The game uses the directory "~\Documents\Square Enix\FINAL FANTASY X&X-2 HD Remaster\" to store it's configuration files. Adding an additional UnX directory to contain UnX's own config files seems like a logical choice.

**Comment by Nariaftw** [comment]
Personally I'd rather not have it cluttering the userprofile directory.

UnX doesn't have an installer/uninstaller. Those files would just rot there forever for most people. I don't see the point.

I get that's convention, but why bother?

**Comment by MeStinkBAD** [comment]
It wouldn't be cluttering since the game creates the directory **%userprofile%\Documents\Square Enix\FINAL FANTASY X&X-2 HD Remaster\** to store saved games and configurations.

If you need more insight into the home directory please check [https://en.wikipedia.org/wiki/Home_directory](url)

**Comment by Nariaftw** [comment]
I understand how it works, but my point being it's more files that would just rot there as there is nothing that would remove them, unless of course uninstalling from steam just rm -rf's ~/Documents/Square Enix/FINAL FANTASY X&X-2 HD Remaster/ but usually that doesn't happen.

**Comment by MeStinkBAD** [comment]
If you run the game, you have the directory ~/Documents/Square Enix/FINAL FANTASY X&X-2 HD Remaster/. Go to run and type "%userprofile%\Documents\Square Enix\FINAL FANTASY X&X-2 HD Remaster\" and see for yourself.

**Comment by Nariaftw** [comment]
I understand, I never said otherwise. That says nothing of the files that would be orphaned inside of it.

**Comment by Kaldaien** [comment]
Everything in that directory winds up in the cloud. It's bad enough that the game's graphics config winds up there.

I have to change all of my settings every time I switch from my desktop to my laptop since there's not a snowball's chance in hell that my laptop can do 4K w/ 8x MSAA. The mod's settings are even more machine-specific than the graphics settings, and I don't want its config winding up in the cloud.

As for the config files being overwritten, this is by design. Stuff that's in active development stays in config files that ship with the software. User preferences for features that are stable go into separate config files that are generated on first run.

I'll revisit the design eventually, but I definitely will not be placing ANY files in the profile directory.

**Comment by MeStinkBAD** [comment]
Then store the hardware config in ~/appdata/local/ directory. It's what You can learn from the developers mistake and place the hardware config there, but don't blame Steam Cloud (which you may disable) for doing what today is considered standard practice.

**Comment by Kaldaien** [comment]
I don't want to disable the Steam cloud, because I want my saves synchronized.

`dxgi.dll` has no idea what game is running, so it has no choice but to look in the current working directory for its ini file. It starts up and imports the plug-in (`unx.dll`, which ***is*** game specific). Only the config for UnX can be re-rooted to the user profile directory and at that point, it's pretty silly to split the config across multiple directories.

Since I'm already rooting the resources directory on the install drive rather than the boot drive, I don't see anything wrong with the current design. If it makes you happy, I can move everything to a sub-directory called cfg, but there's always going to be at least one ini file floating around with the two DLLs and the UnX_Res directory.

**Comment by MeStinkBAD** [comment]
You let the user decide. Keep the existing files where and treat them as the defaults. The users should be in the %userprofile% directory. This allows a convenient way of editing configurations files and still provide the user with an easy way to check the default values. Then include a **useInstallDirectory** option either set to true or false.

**Comment by MeStinkBAD** [comment]
Let me guess what the next response will be: Forward my idea to the authors of dxgi.

**Comment by Kaldaien** [comment]
Eh? It's pretty clear you're just trolling now.

I am the author of dxgi.

**Comment by MeStinkBAD** [comment]
The details listed for the author of dxgi under file properties do not match that of unx. Rather the dxgi's author point to a generic group name, where as unx point to you specifically. I was mistakenly lead to believe that you we're thus not the author. I'm sorry.
